export const USER_FETCH_LIST = 'USER_FETCH_LIST';
export const USER_FETCH_LIST_SUCCESS = 'USER_FETCH_LIST_SUCCESS';
export const USER_FETCH_LIST_FAILURE = 'USER_FETCH_LIST_FAILURE';
export const USER_FETCH = 'USER_FETCH';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_FETCH_FAILURE = 'USER_FETCH_FAILURE';
